default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres

development:
  <<: *default
  database: cacklist_development

test:
  <<: *default
  database: cacklist_test

production:
  <<: *default
  database: cacklist_production
  username: <%= ENV.fetch('DATABASE_USERNAME', 'cacklist') %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
